module = "github.com/astaxie/beego"
package = "github.com/astaxie/beego/session"

description = """
An attacker can craft a malicious URL which lead to XSS due to
usage of unsantized user controlled URL parameters.
"""

credit = "@Kevil-hui"

published = "2021-04-14T12:00:00Z"

[[versions]]
fixed = "v1.12.2"

[links]
commit = "https://github.com/beego/beego/commit/6eeea141d885c16c2a01349d57da62c6379a45a2"
pr = "https://github.com/beego/beego/pull/4018"
context = ["https://github.com/beego/beego/issues/3983"]