module = "github.com/documize/community"
package = "github.com/documize/community/domain/section/markdown"

description = """
HTML content in mardkwon is not santized during rendering, possibly allowing
XSS if used to render untrusted user input.
"""

cve = "CVE-2019-19619"

symbols = ["Provider.Render"]

[[versions]]
fixed = "v1.76.3-0.20191119114751-a4384210d4d0"

[links]
commit = "https://github.com/documize/community/commit/a4384210d4d0d6b18e6fdb7e155de96d4a1cf9f3"