module = "github.com/shiyanhui/dht"

description = """
A malicious peer can craft messages which will cause panics due to
unchecked type assertions.
"""

credit = "@hMihaiDavid"

published = "2021-04-14T12:00:00Z"

[links]
context = ["https://github.com/shiyanhui/dht/issues/57"]