module = "gorm.io/gorm"

description = """
Multiple methods are vulnerable to blind SQL injection attacks
due to constructing SQL statements using unsantized user input.
"""

credit = "@wahyuhadi"

symbols = ["Scope.buildCondition"]

[[versions]]
fixed = "v0.2.0"

[links]
commit = "https://github.com/go-gorm/gorm/commit/836fb2c19d84dac7b0272958dfb9af7cf0d0ade4"
context = ["https://github.com/go-gorm/gorm/issues/2517"]