module = "github.com/tidwall/gjson"

description = """
Maliciously crafted JSON messages can cause an out-of-bounds panic.
"""

cve = "CVE-2020-35380"

credit = "@toptotu"

symbols = ["sqaush"]

published = "2021-04-14T12:00:00Z"

[[versions]]
fixed = "v1.6.4"

[links]
commit = "https://github.com/tidwall/gjson/commit/f0ee9ebde4b619767ae4ac03e8e42addb530f6bc"
context = ["https://github.com/tidwall/gjson/issues/192"]