package = "github.com/gin-gonic/gin"

description = """
An attacker can spoof their source IP address by setting the X-Forwarded-For
HTTP header to an arbitrary value.
"""

credit = "@nl5887"

symbols = ["Context.ClientIP"]

[[versions]]
fixed = "v0.5.0"

[links]
commit = "https://github.com/gin-gonic/gin/commit/0099840c98ae1473c5ff0f18bc93a8e13ceed829"