module = "github.com/gin-gonic/gin"

description = """
An attacker can spoof their source IP address by setting the X-Forwarded-For
HTTP header to an arbitrary value.
"""

credit = "@nl5887"

symbols = ["Context.ClientIP"]

published = "2021-04-14T12:00:00Z"

[[versions]]
fixed = "v0.0.0-20141229113116-0099840c98ae"

[links]
commit = "https://github.com/gin-gonic/gin/commit/0099840c98ae1473c5ff0f18bc93a8e13ceed829"