module = "github.com/buger/jsonparser"

description = """
Malicious input can cause an out-of-bounds panic.
"""

cve = "CVE-2020-35381"

credit = "@toptotu"

symbols = ["searchKeys"]

[[versions]]
fixed = "v1.1.1"

[links]
commit = "https://github.com/buger/jsonparser/commit/df3ea76ece10095374fd1c9a22a4fb85a44efc42"
pr = "https://github.com/buger/jsonparser/pull/221"
context = ["https://github.com/buger/jsonparser/issues/219"]