module = "github.com/cloudflare/golz4"

description = """
LZ4 bindings used a deprecated C API that is vulnerable to
memory corruption which could lead to arbitrary code execution
if successfully exploited.
"""

credit = "Don A. Bailey"

symbols = ["Uncompress"]

published = "2021-04-14T12:00:00Z"

[[versions]]
fixed = "v0.0.0-20140711154735-199f5f787806"

[links]
commit = "https://github.com/cloudflare/golz4/commit/199f5f7878062ca17a98e079f2dbe1205e2ed898"
context = ["https://github.com/cloudflare/golz4/issues/5"]