steps:
  - name: golang
    entrypoint: bash
    args: ["-c", "go run golang.org/x/vulndb/cmd/gendb -reports reports -out /workspace/db"]
  - name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args: ["./deploy/gcp-deploy.sh"]